[package]
name = "terrapoker"
version = "0.1.0"
authors = ["Terra Poker Team"]
edition = "2021"
description = "Protocol Contracts for Terra Poker"
license = "Apache-2.0"
repository = "https://github.com/terra-poker/contracts.git"
homepage = "https://terra-poker.games"
documentation = "https://docs.terra-poker.games"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
thiserror = { version = "1.0.31" }
schemars = { version = "0.8.10" }
serde = { version = "1.0.139", default-features = false, features = ["derive"] }

cosmwasm-std = { version = "1.0.0" }
cw20 = { version = "0.13.4" }
cw20-base = { version = "0.13.4", features = ["library"]}

[dev-dependencies]